"use client";

import { Modal } from "@/components/Modal";
import type { Proposal } from "@/lib/api";

export function ProposalModal({
  proposal,
  partnerName,
  score,
  onClose,
}: {
  proposal: Proposal;
  partnerName: string;
  score?: number;
  onClose: () => void;
}) {
  const generatedDate = new Date(proposal.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Modal title="Collaboration Proposal" onClose={onClose}>
      <p className="font-mono text-[11px] uppercase tracking-widest text-ink-light mb-4">
        Generated by Threadwork AI · {generatedDate}
        {typeof score === "number" && ` · Compatibility ${Math.round(score)}/100`}
      </p>

      <h4 className="font-display text-xl mb-3">{proposal.title}</h4>
      <p className="text-sm text-ink-light leading-relaxed mb-4">{proposal.summary}</p>

      {proposal.terms?.referral_structure && (
        <p className="text-sm mb-3">
          <strong className="font-medium">Referral structure: </strong>
          {proposal.terms.referral_structure}
        </p>
      )}
      {proposal.terms?.suggested_bundle && (
        <p className="text-sm mb-3">
          <strong className="font-medium">Suggested bundle: </strong>
          {proposal.terms.suggested_bundle}
        </p>
      )}
      {proposal.terms?.next_steps && proposal.terms.next_steps.length > 0 && (
        <div className="text-sm mb-4">
          <strong className="font-medium">Next steps:</strong>
          <ul className="mt-1 space-y-1">
            {proposal.terms.next_steps.map((step, i) => (
              <li key={i}>· {step}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex justify-between text-xs font-mono text-ink-light border-t border-line pt-4 mt-4">
        <span>You — Owner</span>
        <span>{partnerName} — Owner</span>
      </div>
    </Modal>
  );
}